"""Initial migration

Revision ID: 28a6594d31a7
Revises: 
Create Date: 2024-04-01 19:46:01.851672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28a6594d31a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_ai_user_conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BIGINT(), nullable=False),
    sa.Column('channel_id', sa.BIGINT(), nullable=False),
    sa.Column('conversation_start_date', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('jsonb_array_length(messages) <= 100', name='max_messages_per_row'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_guild_id_channel_id', 'discord_ai_user_conversation', ['guild_id', 'channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_guild_id_channel_id', table_name='discord_ai_user_conversation')
    op.drop_table('discord_ai_user_conversation')
    # ### end Alembic commands ###
